[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-scene-scheduler"
version = "0.1.0"

[dependencies]
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
log = { workspace = true }
parking_lot = { workspace = true }
database = { path = "../../../utility/database" }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-scene-rendering-gpu-base = { path = "../../rendering/gpu-base" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-device-parallel-compute = { path = "../../../shader/parallel-compute" }
rendiation-shader-library = { path = "../../../shader/library" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
ordered-float = "4.6.0"

[lints]
workspace = true
