[package]
edition = "2024"
name = "query-hook"
version = "0.0.1"

[dependencies]
query = { path = "../query" }
fast-hash-collection = { path = "../fast-hash-collection" }
futures = { workspace = true }
storage = { path = "../storage" }
tracing = { workspace = true }
parking_lot = { workspace = true }
hook = { path = "../hook" }
bumpalo = { workspace = true }

[target.'cfg(not(target = "wasm"))'.dependencies]
rayon = { workspace = true }

[lints]
workspace = true
