[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-rendering-gpu-base"
version = "0.1.0"

[dependencies]

dyn-clone = { workspace = true }
rendiation-algebra = { path = "../../../math/algebra" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
rendiation-scene-core = { path = "../../core" }
reactive = { path = "../../../utility/reactive" }
database = { path = "../../../utility/database" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-webgpu-reactive-utils = { path = "../../../platform/graphics/webgpu-reactive-utils" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture-core = { path = "../../../content/texture/core" }
rendiation-texture-gpu-base = { path = "../../../content/texture/gpu-base" }
rendiation-texture-gpu-system = { path = "../../../content/texture/gpu-system" }
rendiation-lighting-gpu-system = { path = "../../../content/lighting/gpu-system/lighting-system" }
rendiation-device-parallel-compute = { path = "../../../shader/parallel-compute" }
thiserror = { workspace = true }

[lints]
workspace = true
