[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-device-task-graph"
version = "0.1.0"

[dependencies]
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
rendiation-device-parallel-compute = { path = "../parallel-compute" }
rendiation-webgpu-virtual-typed-combine-buffer = { path = "../../platform/graphics/webgpu-virtual-typed-combine-buffer" }
parking_lot = { workspace = true }
dyn-clone = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }
anymap = { path = "../../utility/anymap" }

pollster = { workspace = true } # used in examples

[lints]
workspace = true
