
[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-webgpu-reactive-utils"
version = "0.1.0"

[dependencies]
reactive = { path = "../../../utility/reactive" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture-core = { path = "../../../content/texture/core" }
rendiation-texture-gpu-base = { path = "../../../content/texture/gpu-base" }
rendiation-webgpu = { path = "../webgpu" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[lints]
workspace = true
