# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file

[toolchain]
channel = "nightly-2023-12-25"

# this will auto check and update when compile
# or use `rustup default nightly-2021-xx-xx` update

# before update, please check the toolchain states in
# https://rust-lang.github.io/rustup-components-history/
