[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-device-parallel-compute"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
hook = { path = "../../utility/hook" }
num-traits = "0.2"
dyn-clone = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
pollster = { workspace = true }

[lints]
workspace = true
