[package]
edition = "2021"
name = "rendiation-uri-data-hook"
version = "0.0.1"

[dependencies]
rendiation-abstract-uri-data = { path = "../abstract-uri-data" }
mapped_futures = "0.2.1"
futures = { workspace = true }
query = { path = "../query" }
query-hook = { path = "../query-hook" }
parking_lot = { workspace = true }

[lints]
workspace = true
