[package]
edition = "2021"
name = "reactive"
version = "0.0.1"

[dependencies]
dyn-downcast = { path = "../dyn-downcast" }
fast-hash-collection = { path = "../fast-hash-collection" }
futures = { workspace = true }
pin-project = { workspace = true }
heap-tools = { path = "../heap-tools" }
# incremental = { path = "../incremental" }
reactive-stream = { path = "../reactive-stream" }
reactive-query = { path = "../reactive-query" }
storage = { path = "../storage" }
smallvec = { workspace = true }
dyn-clone = { workspace = true }


# we use it's rwlock to avoid recursive read deadlock
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[lints]
workspace = true
