[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-device-ray-tracing"
version = "0.1.0"

[dependencies]
anymap = { path = "../../utility/anymap" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-shader-library = { path = "../library" }
rendiation-device-task-graph = { path = "../task-graph" }
rendiation-device-parallel-compute = { path = "../parallel-compute" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-space-algorithm = { path = "../../content/space" }
rendiation-webgpu-virtual-buffer = { path = "../../platform/graphics/webgpu-virtual-buffer" }
rendiation-texture-core = { path = "../../content/texture/core" }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
storage = { path = "../../utility/storage" }
parking_lot = { workspace = true }
dyn-clone = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }

pollster = { workspace = true } # used in examples

[dev-dependencies]
rendiation-mesh-generator = { path = "../../content/mesh/generator" }
rendiation-mesh-core = { path = "../../content/mesh/core" }

[lints]
workspace = true
