[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-device-ray-tracing"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-shader-derives = { path = "../derive" }
rendiation-shader-api = { path = "../api" }
rendiation-device-task-graph = { path = "../task-graph" }
rendiation-device-parallel-compute = { path = "../parallel-compute" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-space-algorithm = { path = "../../content/space" }
rendiation-texture-core = { path = "../../content/texture/core" }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
parking_lot = { version = "0.12.1", features = ["send_guard"] }
dyn-clone = { workspace = true }
derivative = { workspace = true }
futures = { workspace = true }
bytemuck = { workspace = true }

pollster = { workspace = true } # used in examples

[lints]
workspace = true
