[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-texture-gpu-system"
version = "0.1.0"

[dependencies]
reactive = { path = "../../../utility/reactive" }
rendiation-webgpu-reactive-utils = { path = "../../../platform/graphics/webgpu-reactive-utils" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-texture-packer = { path = "../packer" }
rendiation-texture-core = { path = "../core" }

[lints]
workspace = true
