[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-shader-api"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true, features = ["derive"] }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
once_cell = { workspace = true }
paste = { workspace = true }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-shader-derives = { path = "../derive" }
wgpu-types = "0.19"

[lints]
workspace = true
