[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-scene-core"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true }
dyn-clone = { workspace = true }
fast-hash-collection = { path = "../../utility/fast-hash-collection" }
futures = { workspace = true }
log = { workspace = true }
once_cell = { workspace = true }
pin-project = { workspace = true }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-animation = { path = "../../content/animation" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-texture-core = { path = "../../content/texture/core" }
rendiation-abstract-uri-data = { path = "../../utility/abstract-uri-data" }
smallvec = { workspace = true }
database = { path = "../../utility/database" }
parking_lot = { workspace = true }
facet = { workspace = true }
serde = { workspace = true }
wgpu-types = { workspace = true }

[lints]
workspace = true
