[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-barycentric-solid-line"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
winit = { workspace = true }

[lints]
workspace = true
