[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-gui-3d"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-scene-core = { path = "../../scene/core" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-mesh-generator = { path = "../../content/mesh/generator" }
database = { path = "../../utility/database" }
reactive = { path = "../../utility/reactive" }
rendiation-state-override = { path = "../state-override" }

[lints]
workspace = true
