[package]
edition = "2021"
name = "virtual-collection"
version = "0.0.1"

[dependencies]
dyn-downcast = { path = "../dyn-downcast" }
fast-hash-collection = { path = "../fast-hash-collection" }
dyn-clone = { workspace = true }
dashmap = { workspace = true }
storage = { path = "../storage" }

# we use it's rwlock to avoid recursive read deadlock
parking_lot = { version = "0.12.1", features = ["send_guard"] }

[lints]
workspace = true
