[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-mesh-lod-graph"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-mesh-core = { path = "../core" }
rendiation-mesh-segmentation = { path = "../segmentation" }
rendiation-mesh-simplification = { path = "../simplification" }

[lints]
workspace = true
