[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-geometry-query"
version = "0.1.0"

[dependencies]
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-mesh-core = { path = "../../content/mesh/core" }
rendiation-texture-core = { path = "../../content/texture/core" }
rendiation-scene-core = { path = "../core" }
reactive = { path = "../../utility/reactive" }
database = { path = "../../utility/database" }

[lints]
workspace = true
