[package]
authors = ["mikialex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-csg-sdf-expression"
version = "0.1.0"

[dependencies]
database = { path = "../../utility/database" }
rendiation-algebra = { path = "../../math/algebra" }
rendiation-geometry = { path = "../../math/geometry" }
rendiation-webgpu = { path = "../../platform/graphics/webgpu" }
rendiation-shader-api = { path = "../../shader/api" }
rendiation-shader-library = { path = "../../shader/library" }
rendiation-webgpu-hook-utils = { path = "../../platform/graphics/webgpu-hook-utils" }
facet = { workspace = true }
serde = { workspace = true }

[lints]
workspace = true
