[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-rendering-gpu-indirect"
version = "0.1.0"

[dependencies]
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
dyn-downcast = { path = "../../../utility/dyn-downcast" }
database = { path = "../../../utility/database" }
log = { workspace = true }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-color = { path = "../../../content/color" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-mesh-core = { path = "../../../content/mesh/core" }
rendiation-mesh-gpu-system = { path = "../../../content/mesh/gpu-system" }
rendiation-scene-core = { path = "../../core" }
rendiation-scene-rendering-gpu-base = { path = "../../rendering/gpu-base" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-shader-library = { path = "../../../shader/library" }
rendiation-texture-core = { path = "../../../content/texture/core" }
rendiation-lighting-gpu-system = { path = "../../../content/lighting/gpu-system/lighting-system" }
rendiation-lighting-punctual = { path = "../../../content/lighting/punctual" }

reactive = { path = "../../../utility/reactive" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-webgpu-reactive-utils = { path = "../../../platform/graphics/webgpu-reactive-utils" }
rendiation-lighting-transport = { path = "../../../content/lighting/transport" }

[lints]
workspace = true
