[package]
authors = ["MikiAlex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-scene-rendering-gpu-ray-tracing"
version = "0.1.0"

[dependencies]
bytemuck = { workspace = true }
database = { path = "../../../utility/database" }
dyn-clone = { workspace = true }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
log = { workspace = true }
anymap = { path = "../../../utility/anymap" }
parking_lot = { workspace = true }
reactive = { path = "../../../utility/reactive" }
rendiation-algebra = { path = "../../../math/algebra" }
rendiation-color = { path = "../../../content/color" }
rendiation-device-ray-tracing = { path = "../../../shader/ray-tracing" }
rendiation-geometry = { path = "../../../math/geometry" }
rendiation-lighting-gpu-system = { path = "../../../content/lighting/gpu-system/lighting-system" }
rendiation-lighting-punctual = { path = "../../../content/lighting/punctual" }
rendiation-lighting-transport = { path = "../../../content/lighting/transport" }
rendiation-texture-gpu-base = { path = "../../../content/texture/gpu-base" }
rendiation-mesh-core = { path = "../../../content/mesh/core" }
rendiation-scene-core = { path = "../../core" }
rendiation-scene-rendering-gpu-base = { path = "../../rendering/gpu-base" }
rendiation-scene-rendering-gpu-indirect = { path = "../../rendering/gpu-indirect" }
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-shader-library = { path = "../../../shader/library" }
rendiation-texture-core = { path = "../../../content/texture/core" }
rendiation-webgpu = { path = "../../../platform/graphics/webgpu" }
rendiation-webgpu-reactive-utils = { path = "../../../platform/graphics/webgpu-reactive-utils" }
rendiation-texture-gpu-process = { path = "../../../content/texture/gpu-process" }
tracing = { workspace = true }

[lints]
workspace = true
