[package]
edition = "2021"
name = "database"
version = "0.0.1"

[dependencies]
fast-hash-collection = { path = "../fast-hash-collection" }
event-source = { path = "../event-source" }
query = { path = "../query" }
arena = { path = "../arena" }
query-hook = { path = "../query-hook" }
futures = { workspace = true }
smallvec = { workspace = true }
storage = { path = "../storage" }
parking_lot = { workspace = true }
dyn-clone = { workspace = true }
facet = { workspace = true }
serde = { workspace = true }
bytemuck = { workspace = true }
rmp-serde = "1.3.0"
disqualified = { workspace = true }
mapped_futures = "0.2.1"
rendiation-abstract-uri-data = { path = "../abstract-uri-data" }

[lints]
workspace = true
