[package]
edition = "2021"
name = "database"
version = "0.0.1"

[dependencies]
fast-hash-collection = { path = "../fast-hash-collection" }
reactive = { path = "../reactive" }
arena = { path = "../arena" }
futures = { workspace = true }
smallvec = { workspace = true }
storage = { path = "../storage" }
parking_lot = { workspace = true }
dyn-clone = { workspace = true }
facet = { workspace = true }

[lints]
workspace = true
