[package]
authors = ["mikialex <18516340862@163.com>"]
edition = "2021"
name = "rendiation-shader-backend-naga"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../../api" }
naga = { workspace = true }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }

[lints]
workspace = true
