
[package]
authors = ["MikiAlex <miikiialexx@gmail.com>"]
edition = "2021"
name = "rendiation-webgpu-hook-utils"
version = "0.1.0"

[dependencies]
rendiation-shader-api = { path = "../../../shader/api" }
rendiation-texture-core = { path = "../../../content/texture/core" }
rendiation-texture-gpu-base = { path = "../../../content/texture/gpu-base" }
rendiation-webgpu = { path = "../webgpu" }
fast-hash-collection = { path = "../../../utility/fast-hash-collection" }
parking_lot = { workspace = true }
hook = { path = "../../../utility/hook" }
query-hook = { path = "../../../utility/query-hook" }
database = { path = "../../../utility/database" }
rendiation-uri-data-hook = { path = "../../../utility/uri-data-hook" }
futures = { workspace = true }
xalloc = "0.2.7"

# used for debug sparse writes not overlap
rangemap = { version = "1.7.0", optional = true }

[lints]
workspace = true

[features]

extra-checks = ["rangemap"]
